### ISSUE TITLE
broken url

### ISSUE THREAD

**Issue by eviau-sat** [antimodular/Best-practices-for-conservation-of-media-art#6]
this returns a 404 for me: https://www.moma.org/explore/inside_out/2015/05/13/open-sourcing-momas-digital-vault/

I can open a MR to remove the URl if needed - i meant, a PR :)

**Comment by stephanschulz** [comment]
I updated the URL to point to the wayback machine but kept visible the original URL
https://web.archive.org/web/20150805115404/moma.org/explore/inside_out/2015/05/13/open-sourcing-momas-digital-vault/
